services:
  envoy:
    restart: always
    container_name: stacks_envoy
    image: envoyproxy/envoy:v1.34.0
    network_mode: "host"
    command: --base-id 3999 --config-path /etc/envoy/envoy.yaml
    volumes:
      - "$PWD/config/envoy.yaml:/etc/envoy/envoy.yaml:ro"
  stacks-blockchain-postgres:
    restart: always
    image: postgres:15.12
    container_name: stacks_postgres
    command: postgres -c 'max_connections=1000'
    shm_size: 2gb
    network_mode: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6nyi11z9tWbXJDYsVESHQfNVo
      POSTGRES_DB: stacks_blockchain_api
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  stacks-blockchain-api:
    restart: always
    image: bestmike007/stacks-blockchain-api:8.9.0
    container_name: stacks_api
    entrypoint: "/wait"
    network_mode: host
    environment:
      WAIT_HOSTS: "127.0.0.1:5432"
      WAIT_COMMAND: "node ./lib/index.js"
      PG_HOST: 127.0.0.1
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: 6nyi11z9tWbXJDYsVESHQfNVo
      PG_DATABASE: stacks_blockchain_api
      PG_SCHEMA: stacks_blockchain_api
      STACKS_CORE_EVENT_HOST: 127.0.0.1
      STACKS_CORE_EVENT_PORT: "3700"
      STACKS_BLOCKCHAIN_API_HOST: 127.0.0.1
      STACKS_BLOCKCHAIN_API_PORT: "23999"
      STACKS_CORE_RPC_HOST: 127.0.0.1
      STACKS_CORE_RPC_PORT: "20443"
      STACKS_CHAIN_ID: "0x00000001"
      STACKS_API_ENABLE_FT_METADATA: 1
      STACKS_API_ENABLE_NFT_METADATA: 1
      NODE_ENV: production
    volumes:
      - ./wait:/wait:ro
  stacks-blockchain:
    restart: always
    image: bestmike007/stacks-blockchain:3.1.0.0.8
    container_name: stacks_node
    entrypoint: "/wait"
    network_mode: host
    environment:
      WAIT_BEFORE: 3
      WAIT_AFTER: 3
      WAIT_HOSTS: "127.0.0.1:3700"
      WAIT_COMMAND: "stacks-node start --config /srv/Stacks.toml"
    volumes:
      - ${STACKS_NODE_TOML:-./config/Stacks.toml}:/srv/Stacks.toml:ro
      - ./stacks-node:/srv/stacks-node
      - ./wait:/wait:ro
