node:
  id: stacks_node_envoy
  cluster: stacks_node
static_resources:
  listeners:
    - address:
        socket_address:
          address: "::"
          port_value: 3999
          ipv4_compat: true
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                internal_address_config:
                  cidr_ranges:
                    address_prefix: 10.0.0.0
                    prefix_len: 8
                stat_prefix: ingress_http
                codec_type: auto
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: stacks_node
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/v2"
                          route:
                            cluster: stacks_core
                        - match:
                            prefix: "/"
                          route:
                            cluster: stacks_api
                      typed_per_filter_config:
                        envoy.filters.http.cors:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy
                          allow_origin_string_match:
                            - prefix: "*"
                          allow_methods: GET, PUT, DELETE, POST, OPTIONS
                          allow_headers: Accept, Accept-Language, Content-Language, Content-Type, Range
                          max_age: "1728000"
  clusters:
    - name: stacks_api
      type: STATIC
      connect_timeout: 10s
      load_assignment:
        cluster_name: stacks_api
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 23999
    - name: stacks_core
      type: STATIC
      connect_timeout: 10s
      load_assignment:
        cluster_name: stacks_core
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 20443
admin:
  access_log:
    - name: envoy.access_loggers.stdout
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 23866
overload_manager:
  resource_monitors:
    - name: "envoy.resource_monitors.global_downstream_max_connections"
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.resource_monitors.downstream_connections.v3.DownstreamConnectionsConfig
        max_active_downstream_connections: 65535
